import { Inter } from "next/font/google";
import "./globals.css";
import Menulist from "@/components/menu/menuList.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="root-container">
          <Menulist />
          <div className="root-content">{children}</div>
        </div>
      </body>
    </html>
  );
}
